/* configDocs.js — descrições curtas das chaves de config do database.json
   Exibidas como label abaixo do nome em cada card do admin.
   Mantido separado para não poluir database/utils.js. */
(function (D) {
    'use strict';

    const DOCS = {
        botName: 'Nome do bot exibido em menus, figurinhas e respostas de IA.',
        prefix: 'Prefixo padrão global (!) — grupos podem ter prefixo próprio via !setprefix (cada ADM altera só seu grupo).',
        newsEnabled: 'Liga/desliga globalmente o serviço de notícias (subreddits).',
        dashboardUrl: 'URL pública do painel, usada em links de divulgação.',
        showLogoInMenu: 'Mostra o logotipo do bot no menu principal do WhatsApp.',
        voiceEffects: 'Aplica efeitos de voz em áudios (TTS) quando ligado.',
        aiModel: 'Modelo usado para IA e resumo de conversas (OpenRouter).',
        aiMaxTokens: 'Máx. de tokens na resposta da IA (corta respostas longas para economizar).',
        aiTemperature: 'Criatividade da IA (0=determinístico, 1=criativo, 2=imprevisível).',
        aiMaxPromptLength: 'Máx. de caracteres no prompt do usuário (corta automaticamente).',
        aiCacheTtl: 'Tempo (ms) que respostas idênticas ficam em cache (0=desliga cache).',
        aiRetryCount: 'Tentativas automáticas se a API falhar (ex.: rate limit).',
        transcribeModel: 'Modelo cloud do !transcrever (ex.: whisper-large-v3-turbo). Vazio = padrao do provedor.',
        transcribeProvider: 'Provedor do !transcrever: auto|groq|openai|openrouter|local (auto = Groq > OpenAI > OpenRouter > offline).',
        transcribeLocalModel: 'Modelo offline do !transcrever: tiny|base|small (faster-whisper, padrao base).',
        transcribeMaxSeconds: 'Duracao maxima (s) aceita pelo !transcrever (padrao 600).',
        openrouterApiKey: 'Chave da API OpenRouter. Salva no .env (não vai pro database.json).',
        summaryLimit: 'Qtde. de mensagens guardadas por grupo para !resumir (alto fluxo).',
        aiPrompt: 'Prompt base da IA. Use {botName} para o nome atual.',
        summaryPrompt: 'Prompt do !resumir — define tom/forma do resumo.',
        stickerPack: 'Nome do pack das figurinhas geradas.',
        stickerAuthor: 'Autor publicado nos EXIF das figurinhas.',

        dashboardEnabled: 'Liga/desliga o painel web do bot.',
        dashboardPort: 'Porta HTTP do painel (3000 por padrão).',
        historyMaxLogs: 'Máx. de linhas do HISTÓRICO (!aidono/!resumir) mantidas antes do trim. Independe do painel.',
        historyHours: 'Janela de retenção do HISTÓRICO em horas (168 = ~7 dias). Independe do painel.',
        historyTrimIntervalMs: 'Intervalo (ms) do trim automático do histórico.',
        historyMuted: 'Pausa a gravação do histórico (!aidono/!resumir). Independe do painel.',
        dashboardMaxLogs: '[LEGADO — alias de historyMaxLogs] Mantido p/ !set antigo.',
        dashboardHistoryHours: '[LEGADO — alias de historyHours] Mantido p/ !set antigo.',
        adminCanControl: 'Permite admins dos grupos controlarem o bot (experimental).',
        clearDefaultLimit: 'Qtde. padrão de mensagens apagadas pelo !limpar.',
        partialWaitMs: 'Espera (ms) no modo parcial antes de responder se nenhum outro bot reagir (padrão 10000; 0=responde direto). Parcial libera mídia + interação + !tts; resto é ignorado em silêncio e moderação fica pausada.',
        newsSubreddits: 'Lista de subreddits monitorados pelo serviço de notícias.',
        newsPollIntervalMinutes: 'Intervalo (min) entre coletas de posts novos.',
        newsUserAgent: 'User-Agent HTTP usado nas requisições ao Reddit.',
        newsSendDelayMs: 'Atraso (ms) entre envios de posts no mesmo grupo.',
        newsFetchStaggerMs: 'Stagger (ms) entre fetches de subreddits diferentes.',
        newsMaxPerCycle: 'Máx. de posts enviados por ciclo de coleta.',
        newsShowMeta: 'Mostra autor/upvotes ao enviar uma notícia.',
        newsRandomSub: 'Embaralha a ordem dos subreddits por ciclo.',
        newsOnePerCycle: 'Envia apenas 1 post por ciclo (evita flood).',
        newsMaxRetries: 'Tentativas em caso de erro ao buscar subreddit.',
        newsRetryBaseDelayMs: 'Atraso base (ms) entre tentativas de retry.',
        dashboardTrimIntervalMs: '[LEGADO — alias de historyTrimIntervalMs] Mantido p/ !set antigo.',
        maxMediaDurationSeconds: 'Duração máxima (s) aceita para mídia enviada.',
        subSessionsGroups: 'Mantém sub-sessões separadas por grupo (anti-colisão).',
        dashboardMuted: '[LEGADO — alias de historyMuted] Mantido p/ compatibilidade.',
        rejectCalls: 'Rejeita ligações 1:1 em silêncio (não tocam no celular do dono). Chamada de grupo não tem rejeição via API.',
        tagOwnerOnMod: 'Marca o dono nos avisos de moderação (antilink/antiflood). Padrão false = nunca marca o dono.',
        dashboardShowQR: 'Mostra o QR Code de conexão no dashboard principal para visitantes.',
        dashboardChatBlocked: 'Bloqueia o envio/recebimento de mensagens no dashboard mantendo o painel admin ativo.',
        linkgrupo: 'Link de divulgação exibido no comando !divulgar.',
        instagramCookies: 'Cookies do Instagram (formato Netscape) para baixar mídias. Cole o conteúdo do cookies.txt aqui.',
        cobaltInstance: 'URL da instância Cobalt (self-host, ex.: http://localhost:9000). Vazio = fallback Cobalt desligado. Instâncias públicas têm bot-protection.',
        cobaltApiKey: 'Api-Key da instância Cobalt (se ela exigir autenticação). Vazio = sem auth.',
        splashEnabled: 'Liga/desliga global do splash de curiosidades (anti-spam: 1x/6h + mín. 60 msgs).',
        splashInterval: 'Mínimo de mensagens para o splash aparecer (60-200, padrão 60).',
        splashWithImage: 'Envia o splash com card de imagem (true) ou só texto (false).',
        splashCooldownMs: 'Janela anti-spam entre dois splashes no mesmo grupo (ms, mín. 6h=21600000, máx. 24h).'
    };

    D.configDocs = DOCS;
})(window.Dashboard = window.Dashboard || {});
