-- Schema Postgres para o Supabase (rode UMA VEZ no SQL Editor do dashboard).
-- Dashboard -> SQL Editor -> New query -> cole este arquivo -> Run.
-- Projeto: smsuzglyliaxbqkrlfki

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jid TEXT NOT NULL,
    push_name TEXT,
    text TEXT NOT NULL,
    time BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_messages_jid_time ON messages(jid, time);

CREATE TABLE IF NOT EXISTS active_groups (
    jid TEXT PRIMARY KEY,
    activated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS active_groups_partial (
    jid TEXT PRIMARY KEY,
    activated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS group_state (
    jid TEXT PRIMARY KEY,
    muted TEXT NOT NULL DEFAULT '[]',
    warnings TEXT NOT NULL DEFAULT '{}',
    antilink INTEGER NOT NULL DEFAULT 1,
    activity TEXT NOT NULL DEFAULT '{}',
    bot_name TEXT,
    menu_image TEXT,
    prefix TEXT,
    sticker_pack TEXT,
    sticker_author TEXT,
    theme TEXT,
    extra TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS stats (
    key TEXT PRIMARY KEY,
    -- TEXT proposital: guarda inteiros (restarts, totalCommands) E strings de mês (_activityMonth/_activityDate = 'YYYY-MM')
    value TEXT NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS dashboard_groups (
    jid TEXT PRIMARY KEY,
    enabled INTEGER NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS dashboard_group_info (
    jid TEXT PRIMARY KEY,
    subject TEXT,
    picture_url TEXT,
    member_count INTEGER NOT NULL DEFAULT 0,
    owner_jid TEXT,
    "desc" TEXT,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS news_groups (
    jid TEXT PRIMARY KEY,
    enabled INTEGER NOT NULL DEFAULT 1,
    activated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS news_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS dashboard_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    grp TEXT,
    text TEXT,
    name TEXT,
    phone TEXT,
    media_json TEXT,
    to_jid TEXT,
    message_id TEXT,
    sender_jid TEXT,
    from_me INTEGER NOT NULL DEFAULT 0,
    hidden INTEGER NOT NULL DEFAULT 0,
    ephemeral INTEGER NOT NULL DEFAULT 0,
    quoted_json TEXT,
    reactions TEXT,
    time_label TEXT,
    timestamp BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dashboard_logs_ts ON dashboard_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_dashboard_logs_to_jid ON dashboard_logs(to_jid, timestamp);
CREATE INDEX IF NOT EXISTS idx_dashboard_logs_msgid ON dashboard_logs(message_id)
    WHERE message_id IS NOT NULL AND message_id <> '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_dashboard_logs_msgid_unique
    ON dashboard_logs(to_jid, message_id, type)
    WHERE message_id IS NOT NULL AND message_id <> '';

CREATE TABLE IF NOT EXISTS dashboard_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT,
    ip TEXT,
    user_agent TEXT,
    timestamp BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dashboard_visits_ts ON dashboard_visits(timestamp);

CREATE TABLE IF NOT EXISTS group_blacklist (
    group_jid TEXT NOT NULL,
    user_jid TEXT NOT NULL,
    added_by TEXT,
    added_at BIGINT NOT NULL,
    PRIMARY KEY (group_jid, user_jid)
);
CREATE INDEX IF NOT EXISTS idx_group_blacklist_group ON group_blacklist(group_jid);

CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL CHECK(kind IN ('bug','sugestao')),
    text TEXT NOT NULL,
    sender_jid TEXT,
    sender_name TEXT,
    group_jid TEXT,
    created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_feedback_kind_created ON feedback(kind, created_at DESC);

CREATE TABLE IF NOT EXISTS antiflood_config (
    jid TEXT PRIMARY KEY,
    enabled INTEGER NOT NULL DEFAULT 1,
    include_admins INTEGER NOT NULL DEFAULT 0,
    max_msgs INTEGER NOT NULL DEFAULT 5,
    window_secs INTEGER NOT NULL DEFAULT 8,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS login_allowed (
    phone TEXT PRIMARY KEY,
    added_by TEXT,
    added_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS group_msg_stats (
    jid TEXT NOT NULL,
    day TEXT NOT NULL,
    hour INTEGER NOT NULL,
    count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (jid, day, hour)
);
CREATE INDEX IF NOT EXISTS idx_group_msg_stats_jid_day ON group_msg_stats(jid, day);

CREATE TABLE IF NOT EXISTS group_modlog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jid TEXT NOT NULL,
    kind TEXT NOT NULL,
    timestamp BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_group_modlog_jid_ts ON group_modlog(jid, timestamp);
CREATE INDEX IF NOT EXISTS idx_group_modlog_jid_kind_ts ON group_modlog(jid, kind, timestamp);

CREATE TABLE IF NOT EXISTS rank_monthly_history (
    jid TEXT NOT NULL,
    month TEXT NOT NULL,
    total INTEGER NOT NULL DEFAULT 0,
    data TEXT NOT NULL DEFAULT '{}',
    created_at BIGINT NOT NULL,
    PRIMARY KEY (jid, month)
);

CREATE TABLE IF NOT EXISTS pessoas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    nome_norm TEXT NOT NULL UNIQUE,
    nascimento TEXT,
    cidade TEXT,
    descricao TEXT,
    status TEXT,
    hobby TEXT,
    pix TEXT,
    instagram TEXT,
    linkedin TEXT,
    foto_path TEXT,
    created_by TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pessoas_cidade ON pessoas(cidade);
CREATE INDEX IF NOT EXISTS idx_pessoas_nascimento ON pessoas(nascimento);

CREATE TABLE IF NOT EXISTS memes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path TEXT NOT NULL,
    hash TEXT NOT NULL UNIQUE,
    sender_jid TEXT,
    sender_name TEXT,
    sender_phone TEXT,
    created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_memes_created ON memes(created_at DESC);
-- meme_sends é anti-repetição local por grupo: NÃO vai para a nuvem.
